name: 错误报告
description: 报告损坏或不正确的行为
title: "[错误报告]: "
labels: [unconfirmed bug]
body:
  - type: markdown
    attributes:
      value: |
        感谢你花时间填写错误。
        如果你需要实时支持，请考虑通过 583799186 加入 QQ 群。

        请注意，此表格仅适用于错误！
  - type: input
    id: intro
    attributes:
      label: 概要
      description: 错误报告的简单摘要
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: |
         你做了什么让它发生。
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: 最少的可复现代码
      description: |
        展示错误的一小段代码。
      render: python
  - type: textarea
    id: expected_result
    attributes:
      label: 预期结果
      description: |
        你期望会发生什么？
    validations:
      required: true
  - type: textarea
    id: actual_result
    attributes:
      label: 实际结果
      description: |
        实际发生了什么？
    validations:
      required: true
  - type: input
    id: intents
    attributes:
      label: Intents
      description: |
        你的机器人使用什么 Intents ？
        这是你传递给客户端的 `qq.Intents` 类。
    validations:
      required: true
  - type: textarea
    id: system
    attributes:
      label: 系统信息
      description: |
        运行 `python -m qq -v` 并在下面粘贴此信息。
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: 清单
      description: |
        让我们确保你在报告此问题时已正确完成搜索！
      options:
        - label: 我已经在未解决的问题中搜索了重复项。
          required: true
        - label: 如果可能的话，我已经展示了整个 traceback。
          required: true
        - label: 如果可见，我已从代码中删除了我的令牌。
          required: true
  - type: textarea
    id: extra
    attributes:
      label: 其他资料
      description: 如果还有什么要说的，请在这里说。
