name: 功能要求
title: "[功能要求]: "
description: 为这个库推荐一个功能
labels: [feature request]
body:
  - type: input
    attributes:
      label: 概要
      description: |
        你的功能请求的简短摘要。
    validations:
      required: true
  - type: dropdown
    attributes:
      multiple: false
      label: 什么是功能请求？
      options:
        - 核心库
        - qq.ext.commands
        - qq.ext.tasks
        - 文档
    validations:
      required: true
  - type: textarea
    attributes:
      label: 问题
      description: |
        你的功能试图解决什么问题？
        实施此功能后，什么变得更容易或可能？
    validations:
      required: true
  - type: textarea
    attributes:
      label: 理想的解决方案
      description: |
        你对问题的理想解决方案是什么？
        你希望此功能做什么？
    validations:
      required: true
  - type: textarea
    attributes:
      label: 当前的解决方案
      description: |
        问题的当前解决方案是什么（如果有）？
    validations:
      required: false
  - type: textarea
    attributes:
      label: 其他资料
      description: 如果还有什么要说的，请在这里说。
